name: chat1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  stomp_dart_client: any
  web_socket_channel: ^3.0.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  cupertino_icons: ^1.0.8
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^19.1.0
  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/chat1.json
