// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtpHPmAAUZDa6a8_vsw8X12oFBLnq-07Q',
    appId: '1:74097996929:web:ed17c596f52c0765098980',
    messagingSenderId: '74097996929',
    projectId: 'chat-8f58d',
    authDomain: 'chat-8f58d.firebaseapp.com',
    storageBucket: 'chat-8f58d.firebasestorage.app',
    measurementId: 'G-QS18Z26J16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPm_lZH8xS9Tduis1xMAkfAX6FK-5Y8U',
    appId: '1:74097996929:android:aecdb8064790cff4098980',
    messagingSenderId: '74097996929',
    projectId: 'chat-8f58d',
    storageBucket: 'chat-8f58d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvvV_JMeC5k5RcrYRHnHNCJWL9-SRk_BQ',
    appId: '1:74097996929:ios:74eac6c3f519e24f098980',
    messagingSenderId: '74097996929',
    projectId: 'chat-8f58d',
    storageBucket: 'chat-8f58d.firebasestorage.app',
    iosBundleId: 'com.example.chat1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtpHPmAAUZDa6a8_vsw8X12oFBLnq-07Q',
    appId: '1:74097996929:web:4a70652e51f1c04b098980',
    messagingSenderId: '74097996929',
    projectId: 'chat-8f58d',
    authDomain: 'chat-8f58d.firebaseapp.com',
    storageBucket: 'chat-8f58d.firebasestorage.app',
    measurementId: 'G-0EWJFC3116',
  );
}
